### ISSUE TITLE
Scenario 3 "move to temple" objective appears before it's a win condition

### ISSUE THREAD

**Issue by stevecotton** [konecnyjakub/Story_of_Wose#1]
Thanks for porting this to 1.14.

In Scenario 3, objectives' [show_if] conditions make the "move to the temple" appear on turn 4, but the dialogue about the temple happens on turn 15. Before turn 15, you don't win from moving to the temple.

**Comment by konecnyjakub** [comment]
I see, I used wrong number in the conditions when I tweaked the code.
